#!/usr/bin/perl

my @chars = map(chr, 32 .. 126);
my @clicks = map {
    /[-'=;\/\\.,\[\] a-z0-9]/ ? 1 : 2;
} @chars;

my %clicks;
@clicks{@chars} = @clicks;

=item
use Data::Dumper;
print Dumper(\%clicks);
exit;
=cut

$keys = 0;

while(<>) {
    chomp;
    s/^\s*//;
    s/\s*$//;

    foreach(split //) {
        if( exists $clicks{$_} ) {
            $keys += $clicks{$_};
        } else {
            warn "Character '$_' was not found\n";
            $clicks{$_} = 0;
        }
    }
}

print "$keys clicks\n";
printf "%.3f Joules\n", $keys*.5*.003*.6;
