#!/usr/bin/perl

use Effort qw(effort);

my $layout = shift;  # get the keyboard layout
my $file   = shift;  # get the filename that should be processed

my $effort = effort(
    layout => $layout,
    file   => $file,
);

my $chars = $effort->{characters};
my $keys  = $effort->{presses};
my $dist  = $effort->{distance};
my $joules= $effort->{joules};

print "$chars characters\n";
print "$keys clicks\n";
print "$dist mm\n";
print "\n";
printf "%.1f mm/click\n", $dist/$keys;
printf "%.1f mm/char\n", $dist/$chars;
printf "%.2f clicks/char\n", $keys/$chars;
printf "%.3f Joules total\n", $joules;

